#template: Hello, %s!

#defaultName: ${DW_DEFAULT_NAME:-Stranger}

# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.cj.jdbc.Driver
    # the username
    user: osmar
    # the password
    password: mysql
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:mysql://127.0.0.1/kudos?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

logging:
  level: INFO
  loggers:
    com.users.app: DEBUG

influxHost: http://localhost:8086
influxDataBase: logs    